version: "3"
services:
  order-beverage-service:
    image: labnicuofm/challenge2ece578:version_1
    hostname: order-beverage-service
    restart: always
    entrypoint: OrderBeverageService

  weather-service:
    image: labnicuofm/challenge2ece578:version_1
    hostname: weather-service
    restart: always
    entrypoint: WeatherService

  getbeverage-service:
    image: labnicuofm/challenge2ece578:version_1
    hostname: getbeverage-service
    restart: always
    entrypoint: GetBeverageService
    
  nginx-thrift:
    image: yg397/openresty-thrift:xenial
    hostname: nginx-thrift
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./nginx_reverse_proxy/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./nginx_reverse_proxy/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./gen-lua:/gen-lua
