/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef GetBeverageService_H
#define GetBeverageService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "vending_machine_types.h"

namespace vending_machine {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class GetBeverageServiceIf {
 public:
  virtual ~GetBeverageServiceIf() {}
  virtual void ReturnBeverage(std::string& _return, const int64_t BeverageType) = 0;
};

class GetBeverageServiceIfFactory {
 public:
  typedef GetBeverageServiceIf Handler;

  virtual ~GetBeverageServiceIfFactory() {}

  virtual GetBeverageServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(GetBeverageServiceIf* /* handler */) = 0;
};

class GetBeverageServiceIfSingletonFactory : virtual public GetBeverageServiceIfFactory {
 public:
  GetBeverageServiceIfSingletonFactory(const ::std::shared_ptr<GetBeverageServiceIf>& iface) : iface_(iface) {}
  virtual ~GetBeverageServiceIfSingletonFactory() {}

  virtual GetBeverageServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(GetBeverageServiceIf* /* handler */) {}

 protected:
  ::std::shared_ptr<GetBeverageServiceIf> iface_;
};

class GetBeverageServiceNull : virtual public GetBeverageServiceIf {
 public:
  virtual ~GetBeverageServiceNull() {}
  void ReturnBeverage(std::string& /* _return */, const int64_t /* BeverageType */) {
    return;
  }
};

typedef struct _GetBeverageService_ReturnBeverage_args__isset {
  _GetBeverageService_ReturnBeverage_args__isset() : BeverageType(false) {}
  bool BeverageType :1;
} _GetBeverageService_ReturnBeverage_args__isset;

class GetBeverageService_ReturnBeverage_args {
 public:

  GetBeverageService_ReturnBeverage_args(const GetBeverageService_ReturnBeverage_args&);
  GetBeverageService_ReturnBeverage_args& operator=(const GetBeverageService_ReturnBeverage_args&);
  GetBeverageService_ReturnBeverage_args() : BeverageType(0) {
  }

  virtual ~GetBeverageService_ReturnBeverage_args() noexcept;
  int64_t BeverageType;

  _GetBeverageService_ReturnBeverage_args__isset __isset;

  void __set_BeverageType(const int64_t val);

  bool operator == (const GetBeverageService_ReturnBeverage_args & rhs) const
  {
    if (!(BeverageType == rhs.BeverageType))
      return false;
    return true;
  }
  bool operator != (const GetBeverageService_ReturnBeverage_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GetBeverageService_ReturnBeverage_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class GetBeverageService_ReturnBeverage_pargs {
 public:


  virtual ~GetBeverageService_ReturnBeverage_pargs() noexcept;
  const int64_t* BeverageType;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _GetBeverageService_ReturnBeverage_result__isset {
  _GetBeverageService_ReturnBeverage_result__isset() : success(false) {}
  bool success :1;
} _GetBeverageService_ReturnBeverage_result__isset;

class GetBeverageService_ReturnBeverage_result {
 public:

  GetBeverageService_ReturnBeverage_result(const GetBeverageService_ReturnBeverage_result&);
  GetBeverageService_ReturnBeverage_result& operator=(const GetBeverageService_ReturnBeverage_result&);
  GetBeverageService_ReturnBeverage_result() : success() {
  }

  virtual ~GetBeverageService_ReturnBeverage_result() noexcept;
  std::string success;

  _GetBeverageService_ReturnBeverage_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const GetBeverageService_ReturnBeverage_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const GetBeverageService_ReturnBeverage_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GetBeverageService_ReturnBeverage_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _GetBeverageService_ReturnBeverage_presult__isset {
  _GetBeverageService_ReturnBeverage_presult__isset() : success(false) {}
  bool success :1;
} _GetBeverageService_ReturnBeverage_presult__isset;

class GetBeverageService_ReturnBeverage_presult {
 public:


  virtual ~GetBeverageService_ReturnBeverage_presult() noexcept;
  std::string* success;

  _GetBeverageService_ReturnBeverage_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class GetBeverageServiceClient : virtual public GetBeverageServiceIf {
 public:
  GetBeverageServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  GetBeverageServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ReturnBeverage(std::string& _return, const int64_t BeverageType);
  void send_ReturnBeverage(const int64_t BeverageType);
  void recv_ReturnBeverage(std::string& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class GetBeverageServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<GetBeverageServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (GetBeverageServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ReturnBeverage(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  GetBeverageServiceProcessor(::std::shared_ptr<GetBeverageServiceIf> iface) :
    iface_(iface) {
    processMap_["ReturnBeverage"] = &GetBeverageServiceProcessor::process_ReturnBeverage;
  }

  virtual ~GetBeverageServiceProcessor() {}
};

class GetBeverageServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  GetBeverageServiceProcessorFactory(const ::std::shared_ptr< GetBeverageServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::std::shared_ptr< GetBeverageServiceIfFactory > handlerFactory_;
};

class GetBeverageServiceMultiface : virtual public GetBeverageServiceIf {
 public:
  GetBeverageServiceMultiface(std::vector<std::shared_ptr<GetBeverageServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~GetBeverageServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<GetBeverageServiceIf> > ifaces_;
  GetBeverageServiceMultiface() {}
  void add(::std::shared_ptr<GetBeverageServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ReturnBeverage(std::string& _return, const int64_t BeverageType) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ReturnBeverage(_return, BeverageType);
    }
    ifaces_[i]->ReturnBeverage(_return, BeverageType);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class GetBeverageServiceConcurrentClient : virtual public GetBeverageServiceIf {
 public:
  GetBeverageServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  GetBeverageServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ReturnBeverage(std::string& _return, const int64_t BeverageType);
  int32_t send_ReturnBeverage(const int64_t BeverageType);
  void recv_ReturnBeverage(std::string& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
